database:
  host: 127.0.0.1         #主机
  port: ${database.host}:13306   #数据库地址
  username: root          #数据库用户名
  password: root          #数据库密码

server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://${database.port}/hot_list?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl