database:
  host: 127.0.0.1         #主机
  port: ${database.host}:3306   #数据库地址
  username: root          #数据库用户名
  password: root          #数据库密码

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${database.port}/hot_list?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:
    timeout: 1000ms # 连接超时时间

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl