name: install&build&push&deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build images with docker
        run: |
          docker build -t ${{ secrets.CLOUD_IMAGE_PREFIX }}:${GITHUB_SHA} .
      - name: tag latest
        run: |
          docker tag ${{ secrets.CLOUD_IMAGE_PREFIX }}:${GITHUB_SHA} ${{ secrets.CLOUD_IMAGE_PREFIX }}:latest

      - name: login to tencent
        run: |
          docker login ccr.ccs.tencentyun.com --username=${{ secrets.CLOUD_USERNAME }} --password=${{ secrets.CLOUD_PASSWORD }}

      - name: push to tencent
        run: |
          docker push ${{ secrets.CLOUD_IMAGE_PREFIX }}:${GITHUB_SHA}
      - name: push latest to tencent
        run: |
          docker push ${{ secrets.CLOUD_IMAGE_PREFIX }}:latest

      - name: install sshpass
        run: |
          sudo apt-get install sshpass

      - name: ssh to cloud
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}

      - name: deploy
        run: |
          sh /sh/deploy_hot_list.sh